version: '3.9'
services:  
    postgresdb:
        image: postgres:14.1-alpine
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
            - ./postgresql/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ui:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - /app/node_modules
            - ./client:/app
        ports:
            - "3000:3000"
    service:
        build:
            context: ./service
            dockerfile: Dockerfile.service
        volumes:
            - /app/node_modules
            - ./service:/app
        links:
            - "postgresdb"
        ports:
            - "4000:4000"
